// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxwuL_CAEX8-MfTCh7dTb6CCAE3z2BUGA',
    appId: '1:418012865597:web:a584336328b75d976cf654',
    messagingSenderId: '418012865597',
    projectId: 'doan2-8a18f',
    authDomain: 'doan2-8a18f.firebaseapp.com',
    storageBucket: 'doan2-8a18f.firebasestorage.app',
    measurementId: 'G-GVYVCG64HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVc6xpxOch7pgK67i1hf-Th9XjecfHH8o',
    appId: '1:418012865597:android:2e47f1fafefdcb1a6cf654',
    messagingSenderId: '418012865597',
    projectId: 'doan2-8a18f',
    storageBucket: 'doan2-8a18f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0TtXIF1QBmDV4or0JBUIHs6hkkvVvsqQ',
    appId: '1:418012865597:ios:f1438530d1f007746cf654',
    messagingSenderId: '418012865597',
    projectId: 'doan2-8a18f',
    storageBucket: 'doan2-8a18f.firebasestorage.app',
    iosBundleId: 'com.example.stour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0TtXIF1QBmDV4or0JBUIHs6hkkvVvsqQ',
    appId: '1:418012865597:ios:f1438530d1f007746cf654',
    messagingSenderId: '418012865597',
    projectId: 'doan2-8a18f',
    storageBucket: 'doan2-8a18f.firebasestorage.app',
    iosBundleId: 'com.example.stour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxwuL_CAEX8-MfTCh7dTb6CCAE3z2BUGA',
    appId: '1:418012865597:web:eda76dccb6199ef26cf654',
    messagingSenderId: '418012865597',
    projectId: 'doan2-8a18f',
    authDomain: 'doan2-8a18f.firebaseapp.com',
    storageBucket: 'doan2-8a18f.firebasestorage.app',
    measurementId: 'G-K3S7S274SC',
  );
}
